#!/usr/bin/env bash
# gemma-research.sh — overnight batch topic research via local Gemma 4 E2B
# Usage: ./gemma-research.sh [topics-file]
#
# Reads topics from a file (one per line) OR uses built-in seed list.
# Runs overnight: generates keyword angles, competitor gaps, H2 outlines.
# Output: public/blog/research/YYYY-MM-DD-[topic].md per topic
#
# Schedule via launchd or run manually before bed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BLOG_DIR="$(dirname "$SCRIPT_DIR")"
RESEARCH_DIR="$BLOG_DIR/research"
TODAY=$(date '+%Y-%m-%d')
TOPICS_FILE="${1:-}"

mkdir -p "$RESEARCH_DIR"

# Default seed topics if no file provided
DEFAULT_TOPICS=(
  "silver price prediction 2026"
  "how to buy silver online safely"
  "silver vs gold which is better investment"
  "silver IRA rollover guide"
  "best time to buy silver"
  "silver rounds vs silver coins"
  "is silver a good investment right now"
  "physical silver vs silver ETF"
  "silver storage at home"
  "silver spot price explained"
)

# Load topics from file or use defaults
if [[ -n "$TOPICS_FILE" && -f "$TOPICS_FILE" ]]; then
  mapfile -t TOPICS < "$TOPICS_FILE"
  echo "Loaded $(echo "${#TOPICS[@]}") topics from $TOPICS_FILE"
else
  TOPICS=("${DEFAULT_TOPICS[@]}")
  echo "Using default seed topics (${#TOPICS[@]} topics)"
fi

echo "Research output dir: $RESEARCH_DIR"
echo "Starting at: $(date '+%H:%M:%S')"
echo "====================================="

COMPLETED=0
FAILED=0

for TOPIC in "${TOPICS[@]}"; do
  [[ -z "$TOPIC" ]] && continue

  SAFE_SLUG=$(echo "$TOPIC" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g' | cut -c1-60)
  OUTFILE="$RESEARCH_DIR/${TODAY}-${SAFE_SLUG}.md"

  # Skip if already done today
  if [[ -f "$OUTFILE" ]]; then
    echo "SKIP (exists): $TOPIC"
    continue
  fi

  echo "Researching: $TOPIC"

  PROMPT="You are a content strategist for Fused Distribution, a silver and precious metals business.

Research topic: \"$TOPIC\"

Produce a structured content brief with these sections:

## Search Intent
One sentence: what does someone searching this actually want?

## Best Angle
The specific angle that differentiates this post from generic results. One sentence.

## Competitor Gap
What do most articles on this topic miss or do poorly? Two sentences.

## Key Points to Cover
5 bullet points — specific, factual, non-obvious. Mark any uncertain stat as [VERIFY].

## Suggested H2 Structure
4-6 H2 headings for the article, in logical order.

## Suggested Title
One SEO-optimized title (60 chars max).

## Internal Link Candidates
2-3 related topics from this list that could be linked internally:
dollar-cost-averaging-silver, silver-coins-rounds-bars, silver-etf-vs-physical, silver-inflation-hedge, silver-portfolio-allocation, silver-premiums-explained, silver-storage-guide, silver-supply-deficit, silver-to-gold-ratio, what-is-junk-silver, where-to-buy-silver

Output the sections above only. No preamble."

  RESPONSE=$(curl -s --max-time 120 http://localhost:11434/api/generate \
    -H "Content-Type: application/json" \
    -d "{
      \"model\": \"gemma4:e2b\",
      \"prompt\": $(echo "$PROMPT" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'),
      \"stream\": false,
      \"options\": {
        \"temperature\": 0.5,
        \"num_predict\": 800
      }
    }" 2>/dev/null)

  if [[ $? -ne 0 ]] || [[ -z "$RESPONSE" ]]; then
    echo "  FAILED: $TOPIC"
    ((FAILED++))
    continue
  fi

  CONTENT=$(echo "$RESPONSE" | python3 -c 'import json,sys; d=json.loads(sys.stdin.read()); print(d.get("response","ERROR"))' 2>/dev/null)

  cat > "$OUTFILE" <<EOF
# Research Brief — $TOPIC
**Date:** $TODAY
**Model:** gemma4:e2b (local, \$0)
**Status:** UNREVIEWED — verify all [VERIFY] markers before use

---

$CONTENT

---
*Generated by gemma-research.sh. Review before using in blog pipeline.*
EOF

  echo "  Saved: $(basename "$OUTFILE")"
  ((COMPLETED++))

  # Brief pause between requests to avoid thermal throttle
  sleep 2
done

echo "====================================="
echo "Done at: $(date '+%H:%M:%S')"
echo "Completed: $COMPLETED | Skipped (existing): $((${#TOPICS[@]} - COMPLETED - FAILED)) | Failed: $FAILED"
echo "Review files in: $RESEARCH_DIR"
